version: '3.8'
services:
  movies:
    image: akashkanaparthi/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: akashkanaparthi/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: akashkanaparthi/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: hpakala53/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
